# Generated by Django 3.2.16 on 2023-06-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_create_category', 'Can create category')], 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('can_create_location', 'Can create location')], 'verbose_name': 'местоположение', 'verbose_name_plural': 'Местоположения'},
        ),
    ]
