# Generated by Django 3.2.16 on 2023-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20230620_2135'),
        ('blog', '0014_alter_post_image'),
    ]

    operations = [
    ]
